version: '3.8'
services:
  fastapi-backend:
    build: .
    container_name: vpn-backend
    restart: always
    ports:
      - "8880:8000"
    environment:
      - TZ=Asia/Singapore
    volumes:
      - ./vpn_data.db:/app/vpn_data.db
      - /etc/localtime:/etc/localtime:ro