version: '3.8'
services:
  fastapi-backend:
    build: .
    container_name: vpn-backend
    restart: always
    ports:
      # 前面加上 127.0.0.1: 
      - "127.0.0.1:8880:8000"
    volumes:
      - ./vpn.db:/app/vpn.db